WinWaitActive("Opening selenium-server-standalone-3.141.59.jar")
Sleep(2000)
Send("{TAB}")
Sleep(2000)
Send("{TAB}")
Sleep(2000)
Send("{ENTER}")
WinActivate("Enter name of file to save to…")
Sleep(2000)
send("{DELETE}")
Sleep(2000)
ControlSetText("Enter name of file to save to…","","Edit1","D:\Eclipse_WS\Intellipaat_10_March\autoDownload\file1.jar")
Sleep(2000)
ControlClick("Enter name of file to save to…","&Save","Button2")